db:
  image: postgres
  ports:
    - "5432"
web:
  build: .
  environment:
    RAILS_ENV: development
  volumes:
    - .:/usr/src/jelly
  volumes_from:
    - bundle
  ports:
    - "3000:3000"
  links:
    - db
bundle:
  image: jelly_web
  command: echo Done
  volumes:
    - /bundle
